path='data/mnist_extensive_02'
num_weights=6
epochs=100
batch_size=200
distribution=[
  {name='linspace', params=[-2, 2]},
  {name='uniform', params=[-2, 2]},
  {name='constant'},
  {name='lognormal', params=[0, 1]},
]
mnist_size=784#[256, 784]
update_mechanism=['ste', 'ab', 'hybrid']
model=[{growing=true}, {layer_sizes=[64, 64, 64, 64]}]
lr=0.5
repetitions=1#3
